---
title: "Missing value imputation"
author: "McEwen Khundi"
date: "3 October 2018"
output: html_document:
    keep_md: TRUE
    theme: cosmo
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Using the mice package to impute missing 
Resources consulted:

* https://www.coursera.org/learn/missing-data/home/welcome
* The paper on the implementation of the mice package

```{r r echo=FALSE, warning=FALSE, message=FALSE}
library(mice)
library(VIM)
```

```{r r echo=FALSE, warning=FALSE, message=FALSE}
nhanes2

head(nhanes2)

summary(nhanes2)

marginplot(nhanes2[,c("chl","bmi")], col = mdc(1:2), cex = 1.2, cex.lab = 1.2, cex.numbers = 1.3, pch = 19)
```

```{r}
nhanes2.imp <- mice(nhanes2, seed = 23)

summary(nhanes2.imp)

complete(nhanes2.imp, action = 1)
```
### Regression example including imputed data
```{r}
fit <- with(nhanes2.imp, lm(chl ~ age + bmi))
round(summary(pool(fit)), 2)
```
### Diagnostic accuracy of imputed values
```{r}
#Checking the values of bmi
nhanes2.imp$imp$bmi
```

