---
title: "R for data science book club"

subtitle: "Chapter15 factors"

author: |
  | McEwen Khundi
  |
  | London School of Hygiene & Tropical Medicine, UK
  | Malawi-Liverpool-Wellcome Clinical Research Programme, Blantyre, Malawi
  |

date: | 
  | `r format(Sys.time(), "%B %d, %Y")`
  |
  | Table of Contents:
output: 
  html_document:
    df_print: paged
    theme: spacelab
    toc: true
---

<br>

## 1. Backgound


<br>

## 2. Set-up

Load all required packages for analysis.

```{r setup, message=FALSE}
library(tidyverse)    #for data manipulation
library(pmthemes)     #for ggplot themes
library(knitr)        #for tables

```

<br>

## 3. Import datasets

Import data required for the analysis.

```{r import}
x1 <- c("Dec", "Apr", "Jan", "Mar")

x2 <- c("Dec", "Apr", "Jam", "Mar")

#Sorting does not work
sort(x1)

month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", 
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
)

y1 <- factor(x1, levels = month_levels)
y1

sort(y1)

y2 <- factor(x2, levels = month_levels)
y2

y2 <- parse_factor(x2, levels = month_levels)

#levels taken in alphabetical order
#default levels
factor(x1)

#levels according to entry of data
f1 <- factor(x1, levels = unique(x1))
f1
#> [1] Dec Apr Jan Mar
#> Levels: Dec Apr Jan Mar

f2 <- x1 %>% fct_inorder()
f2

levels(f2)



```

<br>

## 4. Tidying and recoding

```{r tidy}
gss_cat

str(gss_cat)

gss_cat %>% 
  count(race)

gss_cat %>% 
  ggplot(aes(race)) + 
  geom_bar()

gss_cat %>% 
  ggplot(aes(race)) +
  geom_bar() +
  scale_x_discrete(drop = FALSE)

#15.4 Modifying factor order
relig_summary <- gss_cat %>%
  group_by(relig) %>%
  summarise(
    age = mean(age, na.rm = TRUE),
    tvhours = mean(tvhours, na.rm = TRUE),
    n = n()
  )
#> `summarise()` ungrouping output (override with `.groups` argument)

ggplot(relig_summary, aes(tvhours, relig)) + geom_point()

ggplot(relig_summary, aes(tvhours, fct_reorder(relig, tvhours))) +
  geom_point()

relig_summary %>%
  mutate(relig = fct_reorder(relig, tvhours)) %>%
  ggplot(aes(tvhours, relig)) +
    geom_point()

rincome_summary <- gss_cat %>%
  group_by(rincome) %>%
  summarise(
    age = mean(age, na.rm = TRUE),
    tvhours = mean(tvhours, na.rm = TRUE),
    n = n()
  )
#> `summarise()` ungrouping output (override with `.groups` argument)

ggplot(rincome_summary, aes(age, fct_reorder(rincome, age))) + geom_point()

ggplot(rincome_summary, aes(age, fct_relevel(rincome, "Not applicable"))) +
  geom_point()

by_age <- gss_cat %>%
  filter(!is.na(age)) %>%
  count(age, marital) %>%
  group_by(age) %>%
  mutate(prop = n / sum(n))

ggplot(by_age, aes(age, prop, colour = marital)) +
  geom_line(na.rm = TRUE)

ggplot(by_age, aes(age, prop, colour = fct_reorder2(marital, age, prop))) +
  geom_line() +
  labs(colour = "marital")

gss_cat %>%
  mutate(marital = marital %>% fct_infreq() %>% fct_rev()) %>%
  ggplot(aes(marital)) +
    geom_bar()

#15.5 Modifying factor levels

gss_cat %>% count(partyid)

gss_cat %>%
  mutate(partyid = fct_recode(partyid,
    "Republican, strong"    = "Strong republican",
    "Republican, weak"      = "Not str republican",
    "Independent, near rep" = "Ind,near rep",
    "Independent, near dem" = "Ind,near dem",
    "Democrat, weak"        = "Not str democrat",
    "Democrat, strong"      = "Strong democrat"
  )) %>%
  count(partyid)

gss_cat %>%
  mutate(partyid = fct_recode(partyid,
    "Republican, strong"    = "Strong republican",
    "Republican, weak"      = "Not str republican",
    "Independent, near rep" = "Ind,near rep",
    "Independent, near dem" = "Ind,near dem",
    "Democrat, weak"        = "Not str democrat",
    "Democrat, strong"      = "Strong democrat",
    "Other"                 = "No answer",
    "Other"                 = "Don't know",
    "Other"                 = "Other party"
  )) %>%
  count(partyid)

gss_cat %>%
  mutate(partyid = fct_collapse(partyid,
    other = c("No answer", "Don't know", "Other party"),
    rep = c("Strong republican", "Not str republican"),
    ind = c("Ind,near rep", "Independent", "Ind,near dem"),
    dem = c("Not str democrat", "Strong democrat")
  )) %>%
  count(partyid)

gss_cat %>%
  mutate(relig = fct_lump(relig)) %>%
  count(relig)

gss_cat %>%
  mutate(relig = fct_lump(relig, n = 10)) %>%
  count(relig, sort = TRUE) %>%
  print(n = Inf)
```

### Working with STATA labelled datasets

```{r stata}
library(haven)

library(labelled)

View(gss_cat)

#factors become labelled values in stata
write_dta(gss_cat, path = here::here("gss_cat.dta"))


#Its possible to copy labels from another dataset with the same variables to another0i
gss_cat_new <- read_dta(file = here::here("gss_cat.dta"))

gss_cat_new_factors <- gss_cat_new %>%
                       mutate(across(where(is.labelled), to_factor))

gss_cat_smal <- read_dta(file = here::here("gss_cat_small.dta"))

gss_cat_smal_labelled <- labelled::copy_labels_from(to=gss_cat_smal, from = gss_cat, .strict = FALSE )


gss_cat_smal_factors <- gss_cat_smal_labelled %>%
                        mutate(across(where(is.labelled), to_factor))

View(gss_cat_new_factors)
```


<br>

## X. Reproducibility

This reproduction of the analysis was run by: 

```{r sysinfo, echo=FALSE, message=FALSE, comment=NA, warning=FALSE}

sysinfo <- Sys.info()

sysinfo <- data.frame(keyName=names(sysinfo), value=sysinfo, row.names=NULL)

sysinfo %>% kable()
```

Analysis was run at **`r Sys.time()`**, and using the following Session Info:

```{r sessioninfo, echo=FALSE, results='markdown', message=FALSE, comment=NA, warning=FALSE}
sessionInfo()
```
